name: MoreCraft
main: de.reelos.recipecreator.RecipeCreator
version: 1.12.2.37
commands:
    reloadRecipes:
        description: Checks on the recipe folder for new recipes
        permisson: morecraft.reloadrecipes
        usage: /<command>